imdb/urls.py
from django.conf.urls import url

from . import views

#url patterns for navigating to different pages
urlpatterns = [
  url(r'^$', views.index, name = 'index'), #route to url /imdb/
  url(r'^movies/(?P<movie_id>[0-9]+)/$', views.movie_detail, name='movie_detail'), #route to url /imdb/movies/1,2,..etc
  url(r'^search/$', views.search, name='search'), #route to url /imdb/search
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^imdb/', include('imdb.urls', namespace='imdb')),
    url(r'^admin/', include(admin.site.urls)),
]

imdb/models.py
from django.db import models

# Create your models here.

#Model for Table Genre
class Genre(models.Model):
  name = models.CharField(max_length = 200)
  def __str__(self):
    return self.name

#Model for Table Director
class Director(models.Model):
  name = models.CharField(max_length = 200)
  def __str__(self):
    return self.name

#Model for Table Movie
class Movie(models.Model):
  name = models.CharField(max_length = 200)
  popularity = models.FloatField()
  imdb_score = models.FloatField()
  director = models.ForeignKey(Director)
  genres = models.ManyToManyField(Genre)
  def __str__(self):
    return self.name

imdb/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Movie
# Create your views here.

#view for main page
def index(request):
  movie_list = Movie.objects.all()
  paginator = Paginator(movie_list, 10) #pagination on main page
  page = request.GET.get('page')
  try:
    movies = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    movies = paginator.page(1)
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    movies = paginator.page(paginator.num_pages)
  return render(request, 'imdb/index.html', {'movies' : movies})

#view for movie detail page
def movie_detail(request, movie_id):
  movie = Movie.objects.get(pk=movie_id)
  return render(request, 'imdb/movies/detail.html', {'movie' : movie})

#view for search results page
def search(request):
  if request.method == "GET":
    search_term = request.GET['search']
  else:
    search_term = request.POST['search']

  movie_list = Movie.objects.filter(name__icontains=search_term) #filtering search request on movie name
  director_list = Movie.objects.filter(director__name__icontains=search_term) #filtering search request on director name
  genre_list = Movie.objects.filter(genres__name__icontains=search_term) #filtering search request on genre name
  final_list = movie_list | director_list | genre_list #appending all the results
  final_list = final_list.distinct();

  paginator = Paginator(final_list,10) #pagination on search results page
  page = request.GET.get('page')
  try:
    movies = paginator.page(page)
  except PageNotAnInteger:
    # If page is not an integer, deliver first page.
    movies = paginator.page(1)
  except EmptyPage:
    # If page is out of range (e.g. 9999), deliver last page of results.
    movies = paginator.page(paginator.num_pages)
  return render(request, 'imdb/movies/search.html', {'movies' : movies, 'search_term' : search_term})

imdb/templates/imdb/comma.html
{% if not forloop.last %}
	{% ifequal forloop.revcounter 2 %}
		 and 
	 {% else %}
	 	, 
 	{% endifequal %}
{% else %}
{% endif %}

imdb/templates/imdb/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Movie Junkie</title>

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'imdb/css/style.css' %}" />
    <!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> -->
  </head>
  <body>
    <div id="content">
      <div class="header">
        <div class="container">
          <div class="navbar">
            <form action="{% url 'imdb:search' %}" method="post">
              {% csrf_token %}
              <div class="container-1">
                <span class="icon"><i class="fa fa-search"></i></span>
                <input type="search" id="search" name="search" placeholder="Search for movies, directors, genres..." />
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="movies">
          {% for movie in movies %}
            <a href="{% url 'imdb:movie_detail' movie.id %}" class="movie-link">
              <div class="movie-card">
                <div class="movie-name">{{movie.name}}</div>
                <div class="genre-list">
                  {% for genre in movie.genres.all %}
                    {{genre.name}}{% include "imdb/comma.html" %}
                  {% endfor %}
                </div>
                <div class="movie-director">{{movie.director.name}}</div>
              </div>
            </a>
          {% endfor %}
        </div>
        <div class="pagination">
          <span class="step-links">
            {% if movies.has_previous %}
                <a href="?page={{ movies.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
            </span>

            {% if movies.has_next %}
                <a href="?page={{ movies.next_page_number }}">next</a>
            {% endif %}
          </span>
        </div>
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  </body>
</html>

imdb/templates/imdb/movies/detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Movie Junkie</title>

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'imdb/css/style.css' %}" />
  </head>
  <body>
    
    <div id="content">
      <div class="container">
        <div class="movie">
          <div class="name"><h3>{{movie.name}}</h3></div>
          <div class="director-name"><strong>Director:- </strong>{{movie.director.name}}</div>
          <div class="imdb_score"><strong>IMDB Score:-</strong> {{movie.imdb_score}}</div>
          <div class="popularity">
            <strong>99Popularity:- </strong> {{movie.popularity}}
          </div>
          <div class="genres">
            <strong>Genre:-</strong> 
            {% for genre in movie.genres.all %}
              {{genre.name}}{% include "imdb/comma.html" %}
            {% endfor %}
          </div>

        </div>
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  </body>
</html>

imdb/templates/imdb/movies/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Movie Junkie</title>

    {% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="{% static 'imdb/css/style.css' %}" />
    <!-- <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"> -->
  </head>
  <body>
    
    <div id="content">
      <div class="header">
        <div class="container">
          <div class="navbar">
            <form action="{% url 'imdb:search' %}" method="post">
              {% csrf_token %}
              <div class="container-1">
                <span class="icon"><i class="fa fa-search"></i></span>
                <input type="search" id="search" value="{{search_term}}" name="search" placeholder="Search for movies" />
              </div>
            </form>
          </div>
        </div>
      </div>
      <div class="container">
        {% if movies|length > 0 %}
        <div class="movies">
          {% for movie in movies %}
            <a href="{% url 'imdb:movie_detail' movie.id %}" class="movie-link">
              <div class="movie-card">
                <div class="movie-name">{{movie.name}}</div>
                <div class="genre-list">
                  {% for genre in movie.genres.all %}
                    {{genre.name}}{% include "imdb/comma.html" %}
                  {% endfor %}
                </div>
                <div class="movie-director">{{movie.director.name}}</div>
              </div>
            </a>
          {% endfor %}
        </div>
        <div class="pagination">
          <span class="step-links">
            {% if movies.has_previous %}
                <a href="?page={{ movies.previous_page_number }}&search={{search_term}}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ movies.number }} of {{ movies.paginator.num_pages }}.
            </span>

            {% if movies.has_next %}
                <a href="?page={{ movies.next_page_number }}&search={{search_term}}">next</a>
            {% endif %}
          </span>
        </div>
        {% else %}
        <h3>No Movies Found.</h3>
        {% endif %}
      </div>
    </div>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
  </body>
</html>